<?php
/**
 * QR Verification Landing — The magic patient moment.
 * When a patient scans a QR code from a physical report,
 * they land here. CNIC-only verification to show the document.
 */
session_start();
require_once dirname(__DIR__) . '/4me/config/db.php';
require_once __DIR__ . '/includes/rate_limit.php';
require_once __DIR__ . '/includes/csrf.php';

$hash = preg_replace('/[^a-f0-9]/i', '', trim($_GET['hash'] ?? ''));
$type = in_array($_GET['type'] ?? '', ['rx', 'sa', 'usg', 'receipt'], true) ? $_GET['type'] : null;

if (empty($hash)) {
    die("Invalid QR code. Please scan the code directly from your printed report.");
}

// ── Find document & patient across all tables ──────────────────────────────────
$doc_patient_id = null;
$doc_type_label = '';
$doc_id = null;
$doc_view_type = '';

$tables = [
    'prescriptions' => ['type' => 'rx', 'label' => 'Prescription', 'id_col' => 'id'],
    'patient_ultrasounds' => ['type' => 'usg', 'label' => 'Ultrasound Report', 'id_col' => 'id'],
    'semen_analyses' => ['type' => 'sa', 'label' => 'Semen Analysis', 'id_col' => 'id'],
    'receipts' => ['type' => 'receipt', 'label' => 'Receipt', 'id_col' => 'id'],
];

foreach ($tables as $table => $meta) {
    if ($doc_patient_id)
        break;
    // If type hint is given, prioritize that table
    if ($type && $meta['type'] !== $type)
        continue;

    try {
        $stmt = $conn->prepare("SELECT id, patient_id FROM {$table} WHERE qrcode_hash = ? LIMIT 1");
        $stmt->bind_param('s', $hash);
        $stmt->execute();
        $row = $stmt->get_result()->fetch_assoc();
        if ($row) {
            $doc_patient_id = $row['patient_id'];
            $doc_id = $row['id'];
            $doc_view_type = $meta['type'];
            $doc_type_label = $meta['label'];
        }
    }
    catch (Exception $e) {
    }
}

// If type hint given but not found, search all tables
if (!$doc_patient_id && $type) {
    foreach ($tables as $table => $meta) {
        if ($doc_patient_id)
            break;
        try {
            $stmt = $conn->prepare("SELECT id, patient_id FROM {$table} WHERE qrcode_hash = ? LIMIT 1");
            $stmt->bind_param('s', $hash);
            $stmt->execute();
            $row = $stmt->get_result()->fetch_assoc();
            if ($row) {
                $doc_patient_id = $row['patient_id'];
                $doc_id = $row['id'];
                $doc_view_type = $meta['type'];
                $doc_type_label = $meta['label'];
            }
        }
        catch (Exception $e) {
        }
    }
}

if (!$doc_patient_id) {
    // Invalid hash — show clean error page
?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Invalid QR — IVF Experts</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Figtree:wght@300;400;500;600;700&family=Noto+Sans:wght@300;400;500;700&display=swap" rel="stylesheet">
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
        <style>
            body { font-family: 'Noto Sans', sans-serif; }
            h2, .font-heading { font-family: 'Figtree', sans-serif; }
            .medical-bg {
                background-color: #F8FAFC;
                background-image: radial-gradient(at 0% 0%, hsla(192, 91%, 91%, 1) 0, transparent 50%), 
                                  radial-gradient(at 50% 0%, hsla(152, 63%, 92%, 1) 0, transparent 50%);
            }
        </style>
    </head>
    <body class="medical-bg min-h-screen flex items-center justify-center p-6 text-slate-900">
        <div class="bg-white border border-slate-200 rounded-[2.5rem] p-10 max-w-sm w-full text-center shadow-xl shadow-slate-200/50">
            <div class="w-16 h-16 bg-rose-50 rounded-2xl flex items-center justify-center mx-auto mb-5">
                <i class="fa-solid fa-qrcode text-rose-500 text-2xl"></i>
            </div>
            <h2 class="text-xl font-bold text-slate-800 mb-2">QR Code Not Found</h2>
            <p class="text-slate-400 text-sm mb-6 font-medium">This QR code is invalid, expired, or was not generated by IVF Experts.</p>
            <a href="index.php" class="block w-full bg-cyan-600 text-white py-4 rounded-2xl font-bold text-sm hover:bg-cyan-700 shadow-lg shadow-cyan-100 transition-all">
                Go to Patient Portal
            </a>
        </div>
    </body>
    </html>
    <?php
    exit;
}

// ── If already authenticated as the correct patient — show document directly ──
if (isset($_SESSION['portal_patient_id']) && $_SESSION['portal_patient_id'] == $doc_patient_id) {
    // Redirect to view.php which handles the document rendering
    header("Location: view.php?type={$doc_view_type}&hash={$hash}");
    exit;
}

// ── CNIC-only mini-verification ────────────────────────────────────────────────
// Fetch patient name and masked CNIC for the hint
try {
    $stmt = $conn->prepare("SELECT first_name, last_name, cnic, phone FROM patients WHERE id = ?");
    $stmt->bind_param('i', $doc_patient_id);
    $stmt->execute();
    $doc_patient = $stmt->get_result()->fetch_assoc();
}
catch (Exception $e) {
    $doc_patient = null;
}

// Mask the CNIC for the hint — show first 5 digits only
$cnic_clean_db = preg_replace('/[^0-9]/', '', $doc_patient['cnic'] ?? '');
$cnic_hint = !empty($cnic_clean_db) ? substr($cnic_clean_db, 0, 5) . '-XXXXXXX-X' : '';

// Phone hint — last 4 digits
$phone_db = $doc_patient['phone'] ?? '';
$phone_hint = !empty($phone_db) ? 'XXXXXX' . substr($phone_db, -4) : '';

$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!csrf_verify()) {
        $error = "Security token mismatch. Please try again.";
    }
    elseif (!check_rate_limit('verify_attempts_' . $hash)) {
        $error = "Too many failed attempts for this document. Please wait a few minutes.";
    }
    else {
        $cnic_input = preg_replace('/[^0-9]/', '', $_POST['cnic'] ?? '');

        if (strlen($cnic_input) < 13) {
            $error = "Please enter your complete 13-digit CNIC number.";
        }
        elseif ($cnic_input !== $cnic_clean_db) {
            $error = "Verification failed. Please enter the 13-digit CNIC number exactly as on your identity card.";
        }
        else {
            // Verified! Set session and redirect to document
            session_regenerate_id(true);
            $_SESSION['portal_patient_id'] = $doc_patient_id;
            $_SESSION['session_start'] = time();
            $_SESSION['last_activity'] = time();
            header("Location: view.php?type={$doc_view_type}&hash={$hash}");
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verify to View — IVF Experts</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Figtree:wght@300;400;500;600;700&family=Noto+Sans:wght@300;400;500;700&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <style>
        body { font-family: 'Noto Sans', sans-serif; }
        h1, h2, .font-heading { font-family: 'Figtree', sans-serif; }
        .medical-bg {
            background-color: #F8FAFC;
            background-image: radial-gradient(at 0% 0%, hsla(192, 91%, 91%, 1) 0, transparent 50%), 
                              radial-gradient(at 50% 0%, hsla(152, 63%, 92%, 1) 0, transparent 50%);
        }
        .white-card {
            background: #FFFFFF;
            border: 1px solid rgba(226, 232, 240, 0.8);
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.02), 0 8px 10px -6px rgba(0, 0, 0, 0.02);
        }
        .clean-input {
            background: #F8FAFC;
            border: 1px solid #E2E8F0;
            color: #1E293B;
            transition: all 0.2s;
        }
        .clean-input:focus {
            background: #FFFFFF;
            border-color: #0891B2;
            box-shadow: 0 0 0 4px rgba(8, 145, 178, 0.1);
            outline: none;
        }
    </style>
</head>
<body class="medical-bg min-h-screen flex items-center justify-center p-6 text-slate-900">

    <!-- Ambient glow -->
    <div class="fixed inset-0 overflow-hidden pointer-events-none" aria-hidden="true">
        <div class="absolute -top-32 -right-32 w-80 h-80 bg-indigo-600/20 rounded-full blur-3xl"></div>
        <div class="absolute -bottom-32 -left-32 w-80 h-80 bg-purple-700/20 rounded-full blur-3xl"></div>
    </div>

    <div class="max-w-md w-full">
        <div class="white-card rounded-[2.5rem] p-8 md:p-10 text-center relative overflow-hidden">
            <!-- Subtle Decorative Element -->
            <div class="absolute -top-12 -right-12 w-32 h-32 bg-cyan-50 rounded-full blur-3xl opacity-60"></div>

            <div class="relative">
                <!-- Document Badge -->
                <div class="inline-flex items-center gap-2 bg-cyan-50 border border-cyan-100 text-cyan-700 px-4 py-2 rounded-full text-[10px] font-bold uppercase tracking-widest mb-6">
                    <i class="fa-solid fa-shield-check"></i>
                    Secure Verification
                </div>

                <!-- Icon -->
                <div class="relative mx-auto w-20 h-20 mb-6">
                    <div class="w-20 h-20 bg-cyan-50 rounded-3xl flex items-center justify-center">
                        <i class="fa-solid fa-file-medical text-cyan-600 text-3xl"></i>
                    </div>
                    <div class="absolute -bottom-2 -right-2 w-8 h-8 bg-cyan-600 rounded-xl flex items-center justify-center shadow-lg shadow-cyan-100">
                        <i class="fa-solid fa-lock-open text-white text-xs"></i>
                    </div>
                </div>

                <!-- Title -->
                <h1 class="text-2xl font-bold text-slate-800 mb-1">Verify Identity</h1>
                <p class="text-slate-500 text-sm mb-2 leading-relaxed">
                    Accessing <span class="text-cyan-600 font-bold"><?php echo htmlspecialchars($doc_type_label); ?></span>
                </p>

                <!-- Patient Name Hint -->
                <?php if (!empty($doc_patient['first_name'])): ?>
                <p class="text-slate-400 text-xs mb-8">
                    Belongs to <span class="text-slate-600 font-bold"><?php echo htmlspecialchars($doc_patient['first_name']); ?></span> · 
                    CNIC: <span class="font-mono text-slate-600 bg-slate-50 px-1.5 py-0.5 rounded"><?php echo substr($cnic_hint, 0, 5); ?>-****-<?php echo substr($cnic_hint, -1); ?></span>
                </p>
                <?php
else: ?>
                <div class="mb-8"></div>
                <?php
endif; ?>

                <!-- Error -->
                <?php if ($error): ?>
                <div class="bg-rose-50 border border-rose-100 text-rose-600 px-4 py-3 rounded-2xl text-xs font-bold mb-6 flex items-center gap-3 text-left">
                    <i class="fa-solid fa-circle-exclamation text-base"></i>
                    <?php echo htmlspecialchars($error); ?>
                </div>
                <?php
endif; ?>

                <!-- CNIC Form -->
                <form action="" method="POST" class="space-y-6">
                    <input type="hidden" name="_csrf" value="<?php echo csrf_token(); ?>">
                    
                    <div>
                        <label class="block text-[10px] font-black uppercase tracking-widest text-slate-400 mb-2.5 ml-1">Identity Confirmation</label>
                        <div class="relative">
                            <i class="fa-solid fa-address-card absolute left-4 top-1/2 -translate-y-1/2 text-slate-300"></i>
                            <input type="text" name="cnic" required
                                   class="clean-input w-full pl-11 pr-4 py-4 rounded-2xl text-sm font-medium placeholder:text-slate-300"
                                   placeholder="Confirm 13-digit CNIC" oninput="formatCNIC(this)">
                        </div>
                    </div>

                    <button type="submit" 
                            class="w-full bg-cyan-600 text-white font-bold py-4 rounded-2xl shadow-lg shadow-cyan-100 hover:bg-cyan-700 hover:-translate-y-1 transition-all active:scale-95">
                        Verify & Unlock
                    </button>

                    <div class="pt-6 border-t border-slate-50 flex flex-col items-center gap-2">
                        <div class="flex items-center gap-4 text-slate-200">
                            <i class="fa-solid fa-shield-check text-lg"></i>
                            <span class="text-[10px] font-black uppercase tracking-wider">Secure Medical Access</span>
                        </div>
                        <p class="text-slate-300 text-[10px] font-bold mt-2">Want to see all your records?</p>
                        <a href="index.php" class="text-cyan-600 hover:text-cyan-700 text-xs font-bold transition-colors">
                             Open Full Dashboard
                        </a>
                    </div>
                </form>
            </div>
        </div>

        <div class="text-center mt-8">
            <p class="text-slate-400 text-[10px] uppercase font-black tracking-widest">Powered by IVF Experts Digital</p>
        </div>
    </div>

    <script>
    function formatCNIC(el) {
        let v = el.value.replace(/\D/g, '').slice(0, 13);
        if (v.length > 12)      v = v.slice(0,5) + '-' + v.slice(5,12) + '-' + v.slice(12);
        else if (v.length > 5)  v = v.slice(0,5) + '-' + v.slice(5);
        el.value = v;
    }
    </script>

</body>
</html>
