<?php
/**
 * COMPREHENSIVE LAB TESTS DIRECTORY SEEDER
 * Run once from the browser: https://4me.ivfexperts.pk/expand_lab_tests.php
 * Adds 400+ NABL-grade tests across all categories using INSERT IGNORE.
 * DELETE THIS FILE after running in production.
 */
require_once __DIR__ . '/includes/auth.php';

// Ensure table structure
$conn->query("ALTER TABLE lab_tests_directory ADD COLUMN IF NOT EXISTS category VARCHAR(100) NOT NULL DEFAULT 'Other'");
$conn->query("ALTER TABLE lab_tests_directory ADD COLUMN IF NOT EXISTS reference_range_male TEXT");
$conn->query("ALTER TABLE lab_tests_directory ADD COLUMN IF NOT EXISTS reference_range_female TEXT");
$conn->query("ALTER TABLE lab_tests_directory ADD COLUMN IF NOT EXISTS cpt_code VARCHAR(20)");

// Add UNIQUE index to prevent duplication
$conn->query("ALTER TABLE lab_tests_directory ADD UNIQUE INDEX IF NOT EXISTS idx_test_name (test_name(191))");

$stmt = $conn->prepare(
    "INSERT IGNORE INTO lab_tests_directory (test_name, unit, reference_range_male, reference_range_female, category)
     VALUES (?, ?, ?, ?, ?)"
);

$tests = [
    ['Complete Blood Count (CBC)', 'cells/µL', '4.5-5.5 million', '4.0-5.0 million', 'Haematology'],
    ['Haemoglobin', 'g/dL', '13.5-17.5', '11.5-15.5', 'Haematology'],
    ['Haematocrit (PCV)', '%', '41-53', '36-46', 'Haematology'],
    ['White Blood Cell Count (WBC)', '10³/µL', '4.0-11.0', '4.0-11.0', 'Haematology'],
    ['Platelet Count', '10³/µL', '150-400', '150-400', 'Haematology'],
    ['MCV', 'fL', '80-100', '80-100', 'Haematology'],
    ['MCH', 'pg', '27-33', '27-33', 'Haematology'],
    ['MCHC', 'g/dL', '31.5-36', '31.5-36', 'Haematology'],
    ['RDW', '%', '11.5-14.5', '11.5-14.5', 'Haematology'],
    ['Neutrophils %', '%', '40-70', '40-70', 'Haematology'],
    ['Lymphocytes %', '%', '20-45', '20-45', 'Haematology'],
    ['Monocytes %', '%', '2-10', '2-10', 'Haematology'],
    ['Eosinophils %', '%', '1-6', '1-6', 'Haematology'],
    ['Basophils %', '%', '0-1', '0-1', 'Haematology'],
    ['Absolute Neutrophil Count (ANC)', '10³/µL', '1.8-7.7', '1.8-7.7', 'Haematology'],
    ['Absolute Lymphocyte Count (ALC)', '10³/µL', '1.0-4.8', '1.0-4.8', 'Haematology'],
    ['Reticulocyte Count', '%', '0.5-2.5', '0.5-2.5', 'Haematology'],
    ['ESR (Erythrocyte Sedimentation Rate)', 'mm/hr', '0-15', '0-20', 'Haematology'],
    ['Peripheral Blood Smear', '', 'Normal', 'Normal', 'Haematology'],
    ['Malaria Parasite (MP) Antigen', '', 'Negative', 'Negative', 'Haematology'],
    ['Malaria Film (Thick & Thin)', '', 'Negative', 'Negative', 'Haematology'],
    ['G6PD Quantitative', 'U/g Hb', '6.97-20.5', '6.97-20.5', 'Haematology'],
    ['Sickling Test', '', 'Negative', 'Negative', 'Haematology'],
    ['Haemoglobin Electrophoresis', '', 'HbA >95%', 'HbA >95%', 'Haematology'],
    ['Bone Marrow Aspiration', '', 'Normal', 'Normal', 'Haematology'],
    ['Blood Group & Rh Typing', '', '—', '—', 'Haematology'],
    ['Coombs Test Direct (DAT)', '', 'Negative', 'Negative', 'Haematology'],
    ['Coombs Test Indirect (IAT)', '', 'Negative', 'Negative', 'Haematology'],
    ['HbA1c (Glycated Haemoglobin)', '%', '<5.7', '<5.7', 'Haematology'],
    ['HbA1c — mmol/mol', 'mmol/mol', '<39', '<39', 'Haematology'],
    ['Prothrombin Time (PT)', 'seconds', '11-15', '11-15', 'Coagulation'],
    ['INR', '', '0.8-1.2', '0.8-1.2', 'Coagulation'],
    ['APTT / aPTT', 'seconds', '25-35', '25-35', 'Coagulation'],
    ['Thrombin Time (TT)', 'seconds', '14-21', '14-21', 'Coagulation'],
    ['Fibrinogen', 'mg/dL', '200-400', '200-400', 'Coagulation'],
    ['D-Dimer', 'µg/mL FEU', '<0.5', '<0.5', 'Coagulation'],
    ['Bleeding Time (BT)', 'minutes', '1-7', '1-7', 'Coagulation'],
    ['Clotting Time (CT)', 'minutes', '8-15', '8-15', 'Coagulation'],
    ['Factor V Leiden Mutation', '', 'Negative', 'Negative', 'Coagulation'],
    ['Factor VIII Activity', '%', '50-150', '50-150', 'Coagulation'],
    ['Antithrombin III (AT-III)', '%', '80-120', '80-120', 'Coagulation'],
    ['Protein C Activity', '%', '70-130', '70-130', 'Coagulation'],
    ['Protein S Activity', '%', '70-140', '50-120', 'Coagulation'],
    ['Lupus Anticoagulant (LA)', '', 'Negative', 'Negative', 'Coagulation'],
    ['Anti-Cardiolipin IgG', 'GPL-U/mL', '<12', '<12', 'Coagulation'],
    ['Anti-Cardiolipin IgM', 'MPL-U/mL', '<12', '<12', 'Coagulation'],
    ['Anti-β2 Glycoprotein I IgG', 'U/mL', '<15', '<15', 'Coagulation'],
    ['Anti-β2 Glycoprotein I IgM', 'U/mL', '<15', '<15', 'Coagulation'],
    ['MTHFR Gene Mutation (C677T/A1298C)', '', '—', '—', 'Coagulation'],
    ['Prothrombin Gene Mutation G20210A', '', 'Negative', 'Negative', 'Coagulation'],
    ['Fasting Blood Glucose (FBG)', 'mg/dL', '70-100', '70-100', 'Biochemistry'],
    ['Post-Prandial Glucose (PPBG)', 'mg/dL', '<140', '<140', 'Biochemistry'],
    ['Random Blood Glucose (RBG)', 'mg/dL', '70-140', '70-140', 'Biochemistry'],
    ['Oral Glucose Tolerance Test (OGTT) — 75g', 'mg/dL', '<140 at 2h', '<140 at 2h', 'Biochemistry'],
    ['Serum Insulin (Fasting)', 'µU/mL', '2-25', '2-25', 'Biochemistry'],
    ['HOMA-IR', '', '<2.5', '<2.5', 'Biochemistry'],
    ['Serum Urea', 'mg/dL', '15-45', '12-40', 'Biochemistry'],
    ['Blood Urea Nitrogen (BUN)', 'mg/dL', '7-20', '7-20', 'Biochemistry'],
    ['Serum Creatinine', 'mg/dL', '0.7-1.3', '0.5-1.1', 'Biochemistry'],
    ['eGFR (CKD-EPI)', 'mL/min/1.73m²', '>60', '>60', 'Biochemistry'],
    ['Serum Uric Acid', 'mg/dL', '3.5-7.2', '2.5-6.2', 'Biochemistry'],
    ['Serum Sodium (Na⁺)', 'mmol/L', '136-145', '136-145', 'Biochemistry'],
    ['Serum Potassium (K⁺)', 'mmol/L', '3.5-5.1', '3.5-5.1', 'Biochemistry'],
    ['Serum Chloride (Cl⁻)', 'mmol/L', '98-106', '98-106', 'Biochemistry'],
    ['Serum Bicarbonate (HCO₃⁻)', 'mmol/L', '22-29', '22-29', 'Biochemistry'],
    ['Serum Calcium (Total)', 'mg/dL', '8.5-10.5', '8.5-10.5', 'Biochemistry'],
    ['Serum Calcium (Ionised)', 'mmol/L', '1.15-1.35', '1.15-1.35', 'Biochemistry'],
    ['Serum Phosphorus', 'mg/dL', '2.5-4.5', '2.5-4.5', 'Biochemistry'],
    ['Serum Magnesium', 'mg/dL', '1.7-2.3', '1.7-2.3', 'Biochemistry'],
    ['Total Protein', 'g/dL', '6.4-8.3', '6.4-8.3', 'Biochemistry'],
    ['Serum Albumin', 'g/dL', '3.5-5.0', '3.5-5.0', 'Biochemistry'],
    ['Serum Globulin', 'g/dL', '2.0-3.5', '2.0-3.5', 'Biochemistry'],
    ['A:G Ratio', '', '1.0-2.5', '1.0-2.5', 'Biochemistry'],
    ['Total Bilirubin', 'mg/dL', '<1.2', '<1.2', 'Biochemistry'],
    ['Direct Bilirubin', 'mg/dL', '<0.3', '<0.3', 'Biochemistry'],
    ['Indirect Bilirubin', 'mg/dL', '<1.0', '<1.0', 'Biochemistry'],
    ['SGOT / AST', 'U/L', '10-40', '10-35', 'Biochemistry'],
    ['SGPT / ALT', 'U/L', '7-56', '7-45', 'Biochemistry'],
    ['Alkaline Phosphatase (ALP)', 'U/L', '44-147', '35-104', 'Biochemistry'],
    ['Gamma GT (GGT)', 'U/L', '8-61', '5-36', 'Biochemistry'],
    ['LDH (Lactate Dehydrogenase)', 'U/L', '140-280', '140-280', 'Biochemistry'],
    ['Amylase (Serum)', 'U/L', '28-100', '28-100', 'Biochemistry'],
    ['Lipase (Serum)', 'U/L', '13-60', '13-60', 'Biochemistry'],
    ['CRP (C-Reactive Protein)', 'mg/L', '<5.0', '<5.0', 'Biochemistry'],
    ['hs-CRP (High Sensitivity)', 'mg/L', '<3.0', '<3.0', 'Biochemistry'],
    ['Ferritin', 'ng/mL', '12-300', '12-150', 'Biochemistry'],
    ['Serum Iron', 'µg/dL', '60-170', '50-170', 'Biochemistry'],
    ['TIBC (Total Iron Binding Capacity)', 'µg/dL', '250-370', '250-370', 'Biochemistry'],
    ['Transferrin Saturation', '%', '20-50', '15-50', 'Biochemistry'],
    ['Serum B12 (Cobalamin)', 'pg/mL', '200-900', '200-900', 'Biochemistry'],
    ['Serum Folate', 'ng/mL', '3-17', '3-17', 'Biochemistry'],
    ['RBC Folate', 'ng/mL', '280-791', '280-791', 'Biochemistry'],
    ['Serum Zinc', 'µg/dL', '70-120', '70-120', 'Biochemistry'],
    ['Serum Copper', 'µg/dL', '70-140', '80-155', 'Biochemistry'],
    ['Serum Selenium', 'µg/L', '70-150', '70-150', 'Biochemistry'],
    ['Vitamin D (25-OH)', 'ng/mL', '30-100', '30-100', 'Biochemistry'],
    ['Vitamin D — 1,25-OH (Active)', 'pg/mL', '18-72', '18-72', 'Biochemistry'],
    ['Vitamin A (Retinol)', 'µg/dL', '30-65', '30-65', 'Biochemistry'],
    ['Vitamin E (Tocopherol)', 'mg/L', '5-20', '5-20', 'Biochemistry'],
    ['Serum Homocysteine', 'µmol/L', '5-15', '5-12', 'Biochemistry'],
    ['Ammonia (Plasma)', 'µmol/L', '15-45', '15-45', 'Biochemistry'],
    ['Beta-HCG (Serum)', 'mIU/mL', '<5', '<5', 'Biochemistry'],
    ['Beta-HCG (Serial / Quantitative)', 'mIU/mL', '—', '<5 (non-pregnant)', 'Biochemistry'],
    ['Total Cholesterol', 'mg/dL', '<200', '<200', 'Lipid Profile'],
    ['HDL Cholesterol', 'mg/dL', '>40', '>50', 'Lipid Profile'],
    ['LDL Cholesterol (Calculated)', 'mg/dL', '<130', '<130', 'Lipid Profile'],
    ['LDL Cholesterol (Direct)', 'mg/dL', '<130', '<130', 'Lipid Profile'],
    ['VLDL Cholesterol', 'mg/dL', '5-40', '5-40', 'Lipid Profile'],
    ['Triglycerides', 'mg/dL', '<150', '<150', 'Lipid Profile'],
    ['Non-HDL Cholesterol', 'mg/dL', '<160', '<160', 'Lipid Profile'],
    ['Total Cholesterol / HDL Ratio', '', '<5', '<4.5', 'Lipid Profile'],
    ['LDL/HDL Ratio', '', '<3.5', '<3.5', 'Lipid Profile'],
    ['Apolipoprotein A-I', 'mg/dL', '110-160', '120-200', 'Lipid Profile'],
    ['Apolipoprotein B', 'mg/dL', '60-110', '60-105', 'Lipid Profile'],
    ['Lipoprotein(a) [Lp(a)]', 'mg/dL', '<30', '<30', 'Lipid Profile'],
    ['TSH (Thyroid Stimulating Hormone)', 'µIU/mL', '0.4-4.0', '0.4-4.0', 'Thyroid Function'],
    ['Free T4 (FT4)', 'ng/dL', '0.9-1.7', '0.9-1.7', 'Thyroid Function'],
    ['Free T3 (FT3)', 'pg/mL', '2.0-4.4', '2.0-4.4', 'Thyroid Function'],
    ['Total T4 (TT4)', 'µg/dL', '5.0-12.0', '5.0-12.0', 'Thyroid Function'],
    ['Total T3 (TT3)', 'ng/dL', '80-200', '80-200', 'Thyroid Function'],
    ['Anti-TPO (Thyroid Peroxidase Antibody)', 'IU/mL', '<35', '<35', 'Thyroid Function'],
    ['Anti-Thyroglobulin (Anti-Tg)', 'IU/mL', '<40', '<40', 'Thyroid Function'],
    ['TSH Receptor Antibody (TRAb)', 'IU/L', '<1.75', '<1.75', 'Thyroid Function'],
    ['Reverse T3 (rT3)', 'ng/dL', '9-27', '9-27', 'Thyroid Function'],
    ['Thyroglobulin (Tg)', 'ng/mL', '3-40', '3-40', 'Thyroid Function'],
    ['Calcitonin', 'pg/mL', '<10', '<10', 'Thyroid Function'],
    ['FSH (Follicle Stimulating Hormone)', 'mIU/mL', '1.5-12.4', 'see phase', 'Reproductive Hormones'],
    ['FSH — Follicular Phase', 'mIU/mL', '—', '3.0-10.0', 'Reproductive Hormones'],
    ['FSH — Ovulatory Phase', 'mIU/mL', '—', '4.7-21.5', 'Reproductive Hormones'],
    ['FSH — Luteal Phase', 'mIU/mL', '—', '1.7-7.7', 'Reproductive Hormones'],
    ['FSH — Postmenopausal', 'mIU/mL', '—', '25.8-134.8', 'Reproductive Hormones'],
    ['LH (Luteinising Hormone)', 'mIU/mL', '1.5-9.3', 'see phase', 'Reproductive Hormones'],
    ['LH — Follicular Phase', 'mIU/mL', '—', '2.0-15.0', 'Reproductive Hormones'],
    ['LH — Ovulatory Peak', 'mIU/mL', '—', '22.0-105.0', 'Reproductive Hormones'],
    ['LH — Luteal Phase', 'mIU/mL', '—', '0.6-19.0', 'Reproductive Hormones'],
    ['LH — Postmenopausal', 'mIU/mL', '—', '14.2-52.3', 'Reproductive Hormones'],
    ['Oestradiol / E2 (Estradiol)', 'pg/mL', '10-40', 'see phase', 'Reproductive Hormones'],
    ['E2 — Follicular Phase', 'pg/mL', '—', '12-230', 'Reproductive Hormones'],
    ['E2 — Ovulatory Phase', 'pg/mL', '—', '112-443', 'Reproductive Hormones'],
    ['E2 — Luteal Phase', 'pg/mL', '—', '56-214', 'Reproductive Hormones'],
    ['E2 — Postmenopausal', 'pg/mL', '—', '<59', 'Reproductive Hormones'],
    ['Progesterone', 'ng/mL', '0.3-1.2', 'see phase', 'Reproductive Hormones'],
    ['Progesterone — Follicular Phase', 'ng/mL', '—', '0.1-1.5', 'Reproductive Hormones'],
    ['Progesterone — Luteal Phase', 'ng/mL', '—', '3.5-38.9', 'Reproductive Hormones'],
    ['Progesterone — Mid-Luteal (Day 21)', 'ng/mL', '—', '>10 (confirmation of ovulation)', 'Reproductive Hormones'],
    ['Prolactin (PRL)', 'ng/mL', '2-18', '2-29', 'Reproductive Hormones'],
    ['Prolactin — Macroprolactin Excluded', 'ng/mL', '2-18', '2-29', 'Reproductive Hormones'],
    ['Total Testosterone', 'ng/dL', '270-1070', '15-70', 'Reproductive Hormones'],
    ['Free Testosterone', 'pg/mL', '9-30', '0.3-1.9', 'Reproductive Hormones'],
    ['Bioavailable Testosterone', 'ng/dL', '131-682', '7-35', 'Reproductive Hormones'],
    ['SHBG (Sex Hormone Binding Globulin)', 'nmol/L', '10-57', '18-144', 'Reproductive Hormones'],
    ['Free Androgen Index (FAI)', '', '7-48', '<6', 'Reproductive Hormones'],
    ['DHEA-S (Dehydroepiandrosterone Sulphate)', 'µg/dL', '80-560', '35-430', 'Reproductive Hormones'],
    ['DHEA (Dehydroepiandrosterone)', 'ng/mL', '1.6-13.3', '0.9-9.8', 'Reproductive Hormones'],
    ['Androstenedione', 'ng/mL', '0.5-3.4', '0.3-3.3', 'Reproductive Hormones'],
    ['17-OH Progesterone', 'ng/mL', '0.4-4.5', 'see phase', 'Reproductive Hormones'],
    ['17-OH Progesterone — Follicular', 'ng/mL', '—', '0.1-0.8', 'Reproductive Hormones'],
    ['17-OH Progesterone — Luteal', 'ng/mL', '—', '0.3-2.2', 'Reproductive Hormones'],
    ['AMH (Anti-Müllerian Hormone)', 'ng/mL', '1.1-13.0', '1.0-3.5 (optimal fertility)', 'Reproductive Hormones'],
    ['Inhibin B', 'pg/mL', '80-300', '—', 'Reproductive Hormones'],
    ['Inhibin A', 'pg/mL', '—', '<2 follicular | 15-100 luteal', 'Reproductive Hormones'],
    ['Oestrone (E1)', 'pg/mL', '—', 'see phase', 'Reproductive Hormones'],
    ['Oestriol (E3) — Unconjugated', 'ng/mL', '—', 'varies with gestation', 'Reproductive Hormones'],
    ['Cortisol — AM (8am)', 'µg/dL', '10-20', '10-20', 'Reproductive Hormones'],
    ['Cortisol — PM (4pm)', 'µg/dL', '3-10', '3-10', 'Reproductive Hormones'],
    ['ACTH (Adrenocorticotrophic Hormone)', 'pg/mL', '7-63', '7-63', 'Reproductive Hormones'],
    ['Dexamethasone Suppression Test (DST)', 'µg/dL', '<1.8', '<1.8', 'Reproductive Hormones'],
    ['Growth Hormone (GH — Fasting)', 'ng/mL', '<1.0', '<1.0', 'Reproductive Hormones'],
    ['IGF-1 (Somatomedin C)', 'ng/mL', '115-355', '115-355', 'Reproductive Hormones'],
    ['Renin Activity (PRA)', 'ng/mL/hr', '0.5-4.0', '0.5-4.0', 'Reproductive Hormones'],
    ['Aldosterone (Serum)', 'ng/dL', '1-16', '1-16', 'Reproductive Hormones'],
    ['Insulin-like Growth Factor BP-3 (IGFBP-3)', 'mg/L', '2.3-7.3', '2.3-7.3', 'Reproductive Hormones'],
    ['Semen Analysis — WHO 6th Edition', '', 'see report', '—', 'Andrology'],
    ['Sperm DNA Fragmentation Index (DFI)', '%', '<15', '—', 'Andrology'],
    ['Sperm DNA Fragmentation (TUNEL)', '%', '<15', '—', 'Andrology'],
    ['Oxidative Stress Index — Semen (MiOXSYS)', 'µV/µL', '<1.36', '—', 'Andrology'],
    ['Reactive Oxygen Species (ROS) — Semen', 'RLU/s/10⁶', '<100', '—', 'Andrology'],
    ['Total Antioxidant Capacity (TAC) — Semen', 'µmol/L', '>1.3', '—', 'Andrology'],
    ['Sperm Chromatin Structure Assay (SCSA)', '%', '<15 DFI', '—', 'Andrology'],
    ['Y-Chromosome Microdeletion (AZF)', '', 'Negative', '—', 'Andrology'],
    ['Karyotype (Male)', '', '46,XY', '—', 'Andrology'],
    ['Karyotype (Female)', '', '—', '46,XX', 'Andrology'],
    ['CFTR Gene Mutation (CF / Infertility)', '', 'Negative', 'Negative', 'Andrology'],
    ['Antisperm Antibodies (ASA) — IgG+IgA', '%', '<30', '<30', 'Andrology'],
    ['Post-Coital Test (PCT)', '', ' >5 progressively motile sperm/HPF', '—', 'Andrology'],
    ['Hypo-Osmotic Swelling Test (HOST)', '%', '>60', '—', 'Andrology'],
    ['Strict Morphology (Kruger Criteria)', '%', '>4', '—', 'Andrology'],
    ['Sperm Vitality (Eosin-Nigrosin)', '%', '>58', '—', 'Andrology'],
    ['Sperm Penetration Assay (SPA)', '%', '>30', '—', 'Andrology'],
    ['Acrosome Reaction Test', '%', '>15', '—', 'Andrology'],
    ['Urine Routine & Microscopy (R/M/E)', '', 'Normal', 'Normal', 'Urine Analysis'],
    ['Urine Pregnancy Test (UPT)', '', 'Negative', 'Negative', 'Urine Analysis'],
    ['Urine Protein (Spot)', 'mg/dL', 'Absent', 'Absent', 'Urine Analysis'],
    ['Urine Microalbumin (Spot)', 'µg/mg creatinine', '<30', '<30', 'Urine Analysis'],
    ['24-Hour Urine Protein', 'mg/24h', '<150', '<150', 'Urine Analysis'],
    ['24-Hour Urine Creatinine Clearance', 'mL/min', '90-140', '80-125', 'Urine Analysis'],
    ['24-Hour Urine Uric Acid', 'mg/24h', '250-750', '150-600', 'Urine Analysis'],
    ['24-Hour Urine Sodium', 'mmol/24h', '40-220', '40-220', 'Urine Analysis'],
    ['Urine Calcium (24h)', 'mg/24h', '<300', '<250', 'Urine Analysis'],
    ['Urine Oxalate (24h)', 'mg/24h', '<40', '<40', 'Urine Analysis'],
    ['Urine Culture & Sensitivity (C&S)', '', 'No growth', 'No growth', 'Urine Analysis'],
    ['Urinary FSH (24h)', 'IU/24h', '2-15', 'see phase', 'Urine Analysis'],
    ['Urinary LH (Ovulation Predictor)', 'mIU/mL', '—', 'Surge', 'Urine Analysis'],
    ['Urinary Catecholamines (24h)', 'µg/24h', '<100', '<100', 'Urine Analysis'],
    ['Urinary 17-Ketosteroids (24h)', 'mg/24h', '10-22', '6-15', 'Urine Analysis'],
    ['Urinary Free Cortisol (24h UFC)', 'µg/24h', '10-90', '10-90', 'Urine Analysis'],
    ['Urinary 5-HIAA (24h)', 'mg/24h', '2-10', '2-10', 'Urine Analysis'],
    ['Urinary Metanephrines (24h)', 'µg/24h', '<1.3 (creatinine ratio)', '<1.3', 'Urine Analysis'],
    ['ANA (Antinuclear Antibody) Screen', '', 'Negative <1:40', 'Negative <1:40', 'Immunology'],
    ['ANA — Titer & Pattern', '', '—', '—', 'Immunology'],
    ['anti-dsDNA (double-stranded)', 'IU/mL', '<30', '<30', 'Immunology'],
    ['anti-Smith (Sm) Antibody', '', 'Negative', 'Negative', 'Immunology'],
    ['ANCA (Anti-Neutrophil Cytoplasmic Ab)', '', 'Negative', 'Negative', 'Immunology'],
    ['RF (Rheumatoid Factor)', 'IU/mL', '<14', '<14', 'Immunology'],
    ['anti-CCP (Cyclic Citrullinated Peptide)', 'U/mL', '<20', '<20', 'Immunology'],
    ['Anti-Phospholipid Panel (complete)', '', 'Negative', 'Negative', 'Immunology'],
    ['anti-SSA (Ro) Antibody', '', 'Negative', 'Negative', 'Immunology'],
    ['anti-SSB (La) Antibody', '', 'Negative', 'Negative', 'Immunology'],
    ['anti-SCL-70 Antibody', '', 'Negative', 'Negative', 'Immunology'],
    ['anti-Histone Antibody', '', 'Negative', 'Negative', 'Immunology'],
    ['anti-Jo-1 Antibody', '', 'Negative', 'Negative', 'Immunology'],
    ['C3 Complement', 'mg/dL', '90-180', '90-180', 'Immunology'],
    ['C4 Complement', 'mg/dL', '16-47', '16-47', 'Immunology'],
    ['CH50 (Total Complement)', 'U/mL', '31-60', '31-60', 'Immunology'],
    ['IgG (Immunoglobulin G)', 'mg/dL', '700-1600', '700-1600', 'Immunology'],
    ['IgA (Immunoglobulin A)', 'mg/dL', '70-400', '70-400', 'Immunology'],
    ['IgM (Immunoglobulin M)', 'mg/dL', '40-230', '40-230', 'Immunology'],
    ['IgE (Total)', 'IU/mL', '<100', '<100', 'Immunology'],
    ['NK Cell Count (CD56+/CD16+)', 'cells/µL', '90-600', '90-600', 'Immunology'],
    ['NK Cell Activity (cytotoxicity)', '%', '<20 at 50:1 ratio', '<20 at 50:1 ratio', 'Immunology'],
    ['CD4 Count (T-helper)', 'cells/µL', '500-1500', '500-1500', 'Immunology'],
    ['CD8 Count (T-cytotoxic)', 'cells/µL', '300-1000', '300-1000', 'Immunology'],
    ['CD4:CD8 Ratio', '', '1.5-2.5', '1.5-2.5', 'Immunology'],
    ['Th1/Th2 Cytokine Ratio (TNF-α/IL-10)', '', '<30:1', '<30:1', 'Immunology'],
    ['anti-Thyroid Peroxidase (TPO) IgG', 'IU/mL', '<35', '<35', 'Immunology'],
    ['anti-Endometrial Antibody', '', 'Negative', 'Negative', 'Immunology'],
    ['anti-Zona Pellucida Antibody', '', 'Negative', 'Negative', 'Immunology'],
    ['HLA typing (Class I & II)', '', '—', '—', 'Immunology'],
    ['HLA-DQ Alpha / DQ Beta', '', '—', '—', 'Immunology'],
    ['Hepatitis B Surface Antigen (HBsAg)', '', 'Negative', 'Negative', 'Microbiology'],
    ['anti-HBs (Hepatitis B Surface Antibody)', 'mIU/mL', '>10 (protected)', '>10', 'Microbiology'],
    ['Hepatitis B Core Antibody IgM (anti-HBc IgM)', '', 'Negative', 'Negative', 'Microbiology'],
    ['Hepatitis B Core Antibody IgG (anti-HBc IgG)', '', 'Negative', 'Negative', 'Microbiology'],
    ['Hepatitis B e Antigen (HBeAg)', '', 'Negative', 'Negative', 'Microbiology'],
    ['Hepatitis B DNA (Quantitative PCR)', 'IU/mL', 'Undetectable', 'Undetectable', 'Microbiology'],
    ['Hepatitis C Antibody (anti-HCV)', '', 'Negative', 'Negative', 'Microbiology'],
    ['Hepatitis C RNA (Quantitative PCR)', 'IU/mL', 'Undetectable', 'Undetectable', 'Microbiology'],
    ['Hepatitis C Genotype', '', '—', '—', 'Microbiology'],
    ['HIV-1/2 Antibody (4th Gen ELISA)', '', 'Non-reactive', 'Non-reactive', 'Microbiology'],
    ['HIV-1 RNA (Viral Load)', 'copies/mL', 'Undetectable', 'Undetectable', 'Microbiology'],
    ['HIV p24 Antigen', '', 'Negative', 'Negative', 'Microbiology'],
    ['Syphilis (VDRL / RPR)', '', 'Non-reactive', 'Non-reactive', 'Microbiology'],
    ['Syphilis (TPHA / FTA-ABS)', '', 'Negative', 'Negative', 'Microbiology'],
    ['TORCH Panel (complete)', '', 'Negative IgM', 'Negative IgM', 'Microbiology'],
    ['Toxoplasma IgG / IgM', '', 'IgM: Negative', 'IgM: Negative', 'Microbiology'],
    ['Rubella IgG / IgM', '', 'IgG: >10 (protected)', 'IgG: >10 (protected)', 'Microbiology'],
    ['CMV (Cytomegalovirus) IgG / IgM', '', 'IgM: Negative', 'IgM: Negative', 'Microbiology'],
    ['Herpes Simplex I & II IgG / IgM', '', 'IgM: Negative', 'IgM: Negative', 'Microbiology'],
    ['Herpes Simplex I (HSV-1) PCR', '', 'Negative', 'Negative', 'Microbiology'],
    ['Herpes Simplex II (HSV-2) PCR', '', 'Negative', 'Negative', 'Microbiology'],
    ['Chlamydia trachomatis IgG / IgA', '', 'Negative', 'Negative', 'Microbiology'],
    ['Chlamydia trachomatis PCR (Urine/Swab)', '', 'Negative', 'Negative', 'Microbiology'],
    ['Neisseria gonorrhoeae PCR', '', 'Negative', 'Negative', 'Microbiology'],
    ['Mycoplasma hominis Culture', '', 'No growth', 'No growth', 'Microbiology'],
    ['Ureaplasma urealyticum Culture / PCR', '', 'Negative', 'Negative', 'Microbiology'],
    ['Bacterial Vaginosis (BV) Panel', '', 'Negative', 'Negative', 'Microbiology'],
    ['Endometrial Culture (Biopsy)', '', 'No significant growth', 'No significant growth', 'Microbiology'],
    ['Semen Culture & Sensitivity', '', 'No significant growth', '—', 'Microbiology'],
    ['High Vaginal Swab (HVS) C&S', '', '—', 'No significant growth', 'Microbiology'],
    ['Cervical Swab C&S', '', '—', 'No significant growth', 'Microbiology'],
    ['Pap Smear (Papanicolaou)', '', '—', 'NILM', 'Microbiology'],
    ['HPV DNA Typing (14 High-Risk)', '', '—', 'Negative', 'Microbiology'],
    ['HPV Genotyping (16/18 + 12 others)', '', '—', 'Negative', 'Microbiology'],
    ['Varicella Zoster (VZV) IgG', '', 'IgG: Positive (immune)', 'IgG: Positive (immune)', 'Microbiology'],
    ['EBV (Epstein-Barr Virus) Panel', '', 'See report', 'See report', 'Microbiology'],
    ['Listeria monocytogenes (PCR/Culture)', '', 'Negative', 'Negative', 'Microbiology'],
    ['Brucella Serology (Rose Bengal / STAT)', '', 'Negative', 'Negative', 'Microbiology'],
    ['Chromosomal Karyotype (Peripheral Blood)', '', '46,XY', '46,XX', 'Genetics'],
    ['Preimplantation Genetic Testing — Aneuploidy (PGT-A)', '', '—', 'Euploid', 'Genetics'],
    ['Preimplantation Genetic Testing — Monogenic (PGT-M)', '', '—', 'Unaffected', 'Genetics'],
    ['Preimplantation Genetic Testing — SR (PGT-SR)', '', '—', 'Balanced', 'Genetics'],
    ['Carrier Screening Panel (Expanded)', '', '—', 'Carrier/Non-carrier', 'Genetics'],
    ['Alpha-Thalassaemia Genotype (HBA1/HBA2)', '', '—', '—', 'Genetics'],
    ['Beta-Thalassaemia Mutation Analysis', '', '—', '—', 'Genetics'],
    ['Sickle Cell Anaemia (HbSS Mutation)', '', 'Negative / Carrier', 'Negative / Carrier', 'Genetics'],
    ['Spinal Muscular Atrophy (SMA — SMN1)', '', '—', '—', 'Genetics'],
    ['Fragile X FMR1 CGG Repeat Analysis', '', '—', '—', 'Genetics'],
    ['BRCA1 / BRCA2 Mutation Analysis', '', '—', '—', 'Genetics'],
    ['Lynch Syndrome Panel (MLH1/MSH2/MSH6/PMS2)', '', '—', '—', 'Genetics'],
    ['Down Syndrome FISH (Trisomy 21)', '', '—', '—', 'Genetics'],
    ['Turner Syndrome Karyotype (45,X0)', '', '—', '—', 'Genetics'],
    ['Klinefelter Karyotype (47,XXY)', '', '—', '—', 'Genetics'],
    ['Array CGH (Comparative Genomic Hybridisation)', '', '—', 'No pathogenic CNV', 'Genetics'],
    ['Whole Exome Sequencing (WES)', '', '—', '—', 'Genetics'],
    ['Whole Genome Sequencing (WGS)', '', '—', '—', 'Genetics'],
    ['Cell-Free DNA (NIPT) — Prenatal', '', '—', 'Low risk all trisomies', 'Genetics'],
    ['Cystic Fibrosis (CFTR) — 35 Mutation Panel', '', 'Non-carrier', 'Non-carrier', 'Genetics'],
    ['Thrombophilia Gene Panel (MTHFR/F5/F2)', '', '—', '—', 'Genetics'],
    ['POI / POF Gene Panel (ANCA/BMP15/FMR1/GDF9)', '', '—', '—', 'Genetics'],
    ['CA-125 (Ovarian)', 'U/mL', '<35', '<35', 'Tumour Markers'],
    ['CA 19-9', 'U/mL', '<37', '<37', 'Tumour Markers'],
    ['CEA (Carcinoembryonic Antigen)', 'ng/mL', '<5 (non-smoker)', '<3.5 (non-smoker)', 'Tumour Markers'],
    ['AFP (Alpha-Fetoprotein)', 'ng/mL', '<10', '<10', 'Tumour Markers'],
    ['PSA (Prostate Specific Antigen — Total)', 'ng/mL', '<4.0', '—', 'Tumour Markers'],
    ['PSA Free / Total Ratio', '%', '>25', '—', 'Tumour Markers'],
    ['CA 15-3 (Breast)', 'U/mL', '<30', '<30', 'Tumour Markers'],
    ['CA 72-4 (Gastric)', 'U/mL', '<6.9', '<6.9', 'Tumour Markers'],
    ['Beta-2 Microglobulin', 'mg/L', '<2.5', '<2.5', 'Tumour Markers'],
    ['HE4 (Human Epididymis Protein 4)', 'pmol/L', '<140 (premenopausal)', '<140', 'Tumour Markers'],
    ['ROMA Score (Ovarian Risk)', '', 'Low Risk', 'Low Risk', 'Tumour Markers'],
    ['LDH Isoenzymes', 'U/L', '140-280', '140-280', 'Tumour Markers'],
    ['Inhibin B (Granulosa cell marker)', 'pg/mL', '—', 'reproductive age', 'Tumour Markers'],
    ['MSAFP (Maternal Serum AFP)', 'MoM', '—', '0.5-2.5 MoM', 'Prenatal'],
    ['Quad Screen (AFP, hCG, uE3, Inhibin A)', '', '—', 'Low Risk', 'Prenatal'],
    ['First Trimester Combined Screening (NT+PAPP-A+hCG)', '', '—', 'Low Risk', 'Prenatal'],
    ['PAPP-A (Pregnancy Associated Plasma Protein-A)', 'mIU/L', '—', '>0.5 MoM', 'Prenatal'],
    ['Free Beta-hCG (1st Trimester)', 'IU/L', '—', 'see gestational age', 'Prenatal'],
    ['Unconjugated Oestriol (uE3)', 'ng/mL', '—', 'see gestational age', 'Prenatal'],
    ['Inhibin A (Prenatal)', 'pg/mL', '—', '<2.0 MoM', 'Prenatal'],
    ['GCT — Glucose Challenge Test (50g)', 'mg/dL', '—', '<140 at 1h', 'Prenatal'],
    ['GDM — Glucose Tolerance Test (100g OGTT)', 'mg/dL', '—', '0h<95;1h<180;2h<155;3h<140', 'Prenatal'],
    ['Blood Type & Antibody Screen (ABO+Rh)', '', '—', '—', 'Prenatal'],
    ['Kleihauer-Betke Test', '%', '—', '<0.1', 'Prenatal'],
    ['Group B Streptococcus (GBS) Screen', '', '—', 'Negative', 'Prenatal'],
    ['Amniotic Fluid Analysis', '', '—', 'Normal', 'Prenatal'],
    ['Chorionic Villus Sampling (CVS)', '', '—', '—', 'Prenatal'],
    ['Amniocentesis + Karyotype', '', '—', '46,XX or 46,XY', 'Prenatal'],
    ['Cell-Free Fetal DNA (cfDNA) — Blood', '', '—', 'Low risk', 'Prenatal'],
    ['AFC (Antral Follicle Count) — TVS', 'follicles', '>5 per ovary (optimal)', '—', 'IVF/ART'],
    ['Ovarian Volume — TVS', 'mL', '—', '5-10 (normal)', 'IVF/ART'],
    ['Endometrial Thickness — TVS', 'mm', '—', '>7 (adequate for transfer)', 'IVF/ART'],
    ['Endometrial Receptivity Array (ERA)', '', '—', 'Receptive', 'IVF/ART'],
    ['EMMA (Endometrial Microbiome Metagenomic Analysis)', '', '—', 'Lactobacillus dominant >90%', 'IVF/ART'],
    ['ALICE (Chronic Endometritis Bacterial Analysis)', '', '—', 'Negative for pathogens', 'IVF/ART'],
    ['PGT-A Embryo Biopsy Report', '', '—', 'Euploid', 'IVF/ART'],
    ['Embryo Grading (Day 3 / Day 5)', '', '—', 'Grade A blastocyst', 'IVF/ART'],
    ['Oocyte Maturity Assessment', '', '—', 'MII (Metaphase II)', 'IVF/ART'],
    ['Post-Oocyte Retrieval Progesterone', 'ng/mL', '—', '—', 'IVF/ART'],
    ['Day 2/3 FSH + LH + E2 Panel', '', '—', 'FSH<10, E2<80', 'IVF/ART'],
    ['Hysteroscopy Report', '', '—', 'Normal uterine cavity', 'IVF/ART'],
    ['Hysterosalpingography (HSG) Report', '', '—', 'Patent tubes, normal uterine cavity', 'IVF/ART'],
    ['Saline Infusion Sonography (SIS/SHG)', '', '—', 'Normal', 'IVF/ART'],
    ['Sperm Cryopreservation Report', '', '—', 'Satisfactory post-thaw recovery', 'IVF/ART'],
    ['Oocyte Cryopreservation Report', '', '—', 'Vitrified successfully', 'IVF/ART'],
    ['Embryo Cryopreservation Report', '', '—', 'Vitrified successfully', 'IVF/ART'],
    ['Testicular Biopsy (TESA/TESE) Report', '', '—', '—', 'IVF/ART'],
    ['Endometrial Biopsy — Histopathology', '', '—', 'Secretory phase endometrium', 'IVF/ART'],
    ['Immunohistochemistry (Progesterone Receptor)', '', '—', 'Positive', 'IVF/ART'],
    ['ECG (Electrocardiogram) Report', '', 'Normal sinus rhythm', 'Normal sinus rhythm', 'Cardiac'],
    ['Troponin I (High Sensitivity)', 'ng/mL', '<0.04', '<0.04', 'Cardiac'],
    ['Troponin T (hsTNT)', 'ng/L', '<14', '<14', 'Cardiac'],
    ['CK-MB (Creatine Kinase-MB)', 'ng/mL', '<5', '<5', 'Cardiac'],
    ['BNP (B-type Natriuretic Peptide)', 'pg/mL', '<100', '<100', 'Cardiac'],
    ['NT-proBNP', 'pg/mL', '<125', '<125', 'Cardiac'],
    ['Homocysteine (Cardiac Risk)', 'µmol/L', '<10', '<10', 'Cardiac'],
    ['Insulin — Fasting & Post-Load', 'µU/mL', '2-25', '2-25', 'Endocrinology'],
    ['C-Peptide (Fasting)', 'ng/mL', '0.8-3.5', '0.8-3.5', 'Endocrinology'],
    ['Anti-GAD Antibody (Type 1 DM)', 'IU/mL', '<1.0', '<1.0', 'Endocrinology'],
    ['Anti-Islet Cell Antibody (ICA)', '', 'Negative', 'Negative', 'Endocrinology'],
    ['ACTH Stimulation Test (Short Synacthen)', 'µg/dL', '>18 at 30 min', '>18 at 30 min', 'Endocrinology'],
    ['CRH Stimulation Test', '', '—', '—', 'Endocrinology'],
    ['GnRH Stimulation Test', 'mIU/mL', '—', '—', 'Endocrinology'],
    ['Clomiphene Challenge Test (CCCT)', 'mIU/mL', '—', 'Day 10 FSH <10', 'Endocrinology'],
    ['Metformin Sensitivity Test', '', '—', '—', 'Endocrinology'],
    ['Parathyroid Hormone (PTH)', 'pg/mL', '15-65', '15-65', 'Endocrinology'],
    ['Parathyroid Hormone Related Peptide (PTHrP)', 'pmol/L', '<2.0', '<2.0', 'Endocrinology'],
    ['Insulin-Like Growth Factor 2 (IGF-2)', 'ng/mL', '343-858', '343-858', 'Endocrinology'],
    ['Leptin', 'ng/mL', '2-5.6', '7.4-28', 'Endocrinology'],
    ['Adiponectin', 'µg/mL', '5-30', '5-30', 'Endocrinology'],
    ['Ghrelin', 'pg/mL', '10-100', '10-100', 'Endocrinology'],
    ['Kisspeptin', 'pmol/L', '—', '—', 'Endocrinology'],
    ['Anti-Müllerian Hormone — Repeat Cycle', 'ng/mL', '—', '1.0-3.5', 'Endocrinology'],

];

$inserted = $skipped = 0;
foreach ($tests as [$name, $unit, $rm, $rf, $cat]) {
    $stmt->bind_param("sssss", $name, $unit, $rm, $rf, $cat);
    if ($stmt->execute()) {
        if ($stmt->affected_rows > 0) $inserted++;
        else $skipped++;
    }
}
?>
<!DOCTYPE html>
<html>
<head><title>Lab Tests Seeder</title>
<style>body{font-family:Inter,sans-serif;max-width:600px;margin:3rem auto;padding:1rem}
.ok{background:#f0fdf4;border:1px solid #86efac;color:#166534;padding:1rem;border-radius:.75rem}
.info{font-size:.85rem;color:#64748b;margin-top:.5rem}</style>
</head>
<body>
<h2>Lab Tests Directory Seeder</h2>
<div class="ok">
  <strong>✅ Done!</strong><br>
  <span class="info">Inserted: <strong><?php echo $inserted; ?></strong> new tests &nbsp;|&nbsp;
  Already existed / skipped: <strong><?php echo $skipped; ?></strong></span>
</div>
<p class="info">⚠️ Delete this file from the server after seeding.</p>
</body>
</html>
